[build]
buildCommand = "cargo build --release && cp target/release/gud-price-service ./gud-price-service"

[deploy]
startCommand = "./gud-price-service"
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
